### ISSUE TITLE
Status cannot be changed to Complete in Kubernetes Cronjob

### ISSUE THREAD

**Issue by FcrbPeter** [Norconex/collector-http#575]
Hi, I am using Kubernetes cronjob to crawl the different websites.
I followed the tutorial [here](https://www.norconex.com/how-to-run-norconex-collector-in-docker/) to create the docker image and use in the Kubernetes.

The crawling process is working well, while the status of that job/pod cannot be marked as Complete after all urls are processed. 

![Screenshot 2019-03-18 at 16 51 09](https://user-images.githubusercontent.com/5670481/54518197-b57c6680-499e-11e9-959e-ddf46027d7d4.png)

The image above shows the status of the jobs, those jobs which are RUNNING, are the completed job with no errors. And the Completed jobs are the processes contain errors.

Is there any workaround to solve this?

**Comment by menglabs** [comment]
Hello,

Would you mind to share the cronjob config of Kubernetes ?

Thanks,
Meng

**Comment by FcrbPeter** [comment]
Hi Meng,

Here is the cronjob config.
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler-cronjob-acer
  labels:
    app: crawler-cronjob
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: collector-job
            image: gcr.io/mygcpproject/my-norconex-http-collector:latest
            command: ["bash", "launch.sh"]
            volumeMounts:
            - name: config-volume
              mountPath: /app/collector/config
            # imagePullPolicy: Never
          volumes:
          - name: config-volume
            configMap:
              name: crawler-config-acer
          restartPolicy: Never
```

Thanks,
Peter Chan

**Comment by menglabs** [comment]
Hello Peter,

Unfortunately, I do not have the GKE. But I have tested it in the minikube on my Mac. 


Based on my test, I am not able to reproduce your case.

The following are my settings:

* The `Dockerfile`, `entrypoint.sh` and `start.sh` are exactly same as them in the [example](https://www.norconex.com/how-to-run-norconex-collector-in-docker/).

* The `es-config.xml` has some changes
1. The searchUrl changes to `http://elasticsearch-master:9200` as the elasticsearch is running in minikube as well.
2. The \<crawler\> section. I pick a simple website with limited pages.

* The `cronjob.yaml`:
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: crawler-cronjob-acer
  labels:
    app: crawler-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: collector-job
            image: norconex-collector:2.8.0
            imagePullPolicy: Never
          restartPolicy: Never
```


Please see the screenshot:

![Screen Shot 2019-03-21 at 3 09 51 PM](https://user-images.githubusercontent.com/8092140/54781323-56169480-4bf2-11e9-919b-47af8f8c3993.png)


**Differences between us:**
1. You are using a `launch.sh` as your start point.
2. The config files of collector are mounted from configMap.

**Suggestions:**
Please double check your `launch.sh` file or anyother script which involves in to see whether there is any command keeping the docker running after the collector completed.


Best,

Meng
